# .github/workflows/webapp-generation.yml

name: Web App Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-webapp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Fetch Prompt Rules from GitHub
      run: |
        curl -s https://raw.githubusercontent.com/likhonsdev/Prompt-Engineering/refs/heads/main/prompt-rules/rules.json -o ./rules.json

    - name: Execute Web App Generation
      run: |
        python generate_webapp.py --rules ./rules.json

    - name: Deploy Web App
      run: |
        # Example command to deploy your web app
        ./deploy.sh
