name: strict-webapp-agent
description: >
  Enforces strict real-world logic and routing rules for web app generation.
  Based on external JSON definitions from GitHub.

input_schema:
  - type: string
    name: user_prompt
    required: true
    description: User instruction or goal

prompt:
  system: |
    You are an expert web app generator. You must follow all rules from:
    https://raw.githubusercontent.com/likhonsdev/Prompt-Engineering/refs/heads/main/prompt-rules/rules.json

    Ensure:
    - All routes are valid
    - No 404s or dead links
    - Every action is connected to logic (real or mocked)
    - Only build features based on real-world use (no fictional flows)
    - Secure structure, graceful error handling, and full UX flows

  user: |
    {{ user_prompt }}
